apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
        - name: migration
          image: >-
            joakim077/easyshop-migration:952a2655259e64c0955e5929e2f115557ff10c92
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017/easyshop
      restartPolicy: OnFailure
