apiVersion: batch/v1
kind: Job
metadata:
  name: db-migration
  namespace: easyshop
spec:
  template:
    spec:
      containers:
        - name: migration
          image: >-
            joakim077/easyshop-migration:ea4e333053a36a5e9c01456be66e72ffb0c2f833
          imagePullPolicy: Always
          env:
            - name: MONGODB_URI
              value: mongodb://mongodb-service:27017/easyshop
      restartPolicy: OnFailure
